//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVcartScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVcartScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cartScanner sent an unexpected value. Expected &quot;{0}&quot;, but received &quot;{1}&quot;..
        /// </summary>
        internal static string ArduinoUnexpectedValueMessage {
            get {
                return ResourceManager.GetString("ArduinoUnexpectedValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data exists on cartridge. Please review troubleshooting section of the manual..
        /// </summary>
        internal static string BlankCartridge {
            get {
                return ResourceManager.GetString("BlankCartridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartScanner Read Error.
        /// </summary>
        internal static string CartridgeReadErrorTitle {
            get {
                return ResourceManager.GetString("CartridgeReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :FINISHED.
        /// </summary>
        internal static string cEndMessage {
            get {
                return ResourceManager.GetString("cEndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ConnectingMessage {
            get {
                return ResourceManager.GetString("ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ 128K CARTRIDGE.
        /// </summary>
        internal static string cRead128kCommand {
            get {
                return ResourceManager.GetString("cRead128kCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ 256K CARTRIDGE.
        /// </summary>
        internal static string cRead256kCommmand {
            get {
                return ResourceManager.GetString("cRead256kCommmand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ 512K CARTRIDGE.
        /// </summary>
        internal static string cRead512KCommand {
            get {
                return ResourceManager.GetString("cRead512KCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ 64K CARTRIDGE.
        /// </summary>
        internal static string cRead64kCommand {
            get {
                return ResourceManager.GetString("cRead64kCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ CARTRIDGE.
        /// </summary>
        internal static string cReadCommand {
            get {
                return ResourceManager.GetString("cReadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVCARTSCANNER.
        /// </summary>
        internal static string cReady {
            get {
                return ResourceManager.GetString("cReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN:.
        /// </summary>
        internal static string cStartMessage {
            get {
                return ResourceManager.GetString("cStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        internal static string cStatus {
            get {
                return ResourceManager.GetString("cStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error..
        /// </summary>
        internal static string FileTooLargeMessage {
            get {
                return ResourceManager.GetString("FileTooLargeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error: File too large.
        /// </summary>
        internal static string FileTooLargeTitle {
            get {
                return ResourceManager.GetString("FileTooLargeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cartridge file is currently loaded..
        /// </summary>
        internal static string NoCartridgeFileLoaded {
            get {
                return ResourceManager.GetString("NoCartridgeFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data In Memory..
        /// </summary>
        internal static string NoCartridgeLoadedMessage {
            get {
                return ResourceManager.GetString("NoCartridgeLoadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error: No Data In Memory.
        /// </summary>
        internal static string NoCartridgeLoadedTitle {
            get {
                return ResourceManager.GetString("NoCartridgeLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartScanner is not found. Please set your serial port by detecting the cartScanner in the Settings menu..
        /// </summary>
        internal static string NoSerialPortsMessage {
            get {
                return ResourceManager.GetString("NoSerialPortsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No serial port set.
        /// </summary>
        internal static string NoSerialPortsTitle {
            get {
                return ResourceManager.GetString("NoSerialPortsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string ProgressMessage {
            get {
                return ResourceManager.GetString("ProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0:#,#} bytes from the cartScanner, but was expecting {1:#,#} bytes..
        /// </summary>
        internal static string UnexpectedCartridgeSize {
            get {
                return ResourceManager.GetString("UnexpectedCartridgeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cartScanner Error.
        /// </summary>
        internal static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
    }
}
